### ISSUE TITLE
More than 3 variables?

### ISSUE THREAD

**Issue by jaysonh** [2bbb/ofxExpression#2]
Hi, nice addon! But just wondering if it's possible to use more than 3 variables? I tried to add a w variable to Expression.h but caused lots of errors. I can't quite follow the logic of the Expression.h file so not sure how to implement extra variables?
Any help would be appreciated!

**Comment by 2bbb** [comment]
@jaysonh 

hi!

I extended `x1 (= x), x2 (= y), x3 (= z), x4 (= w), x5, ..., x10`. and add `fmod` op on **extend_num_arg** branch.
please check it.

https://github.com/2bbb/ofxExpression/tree/dev/extend_num_arg

**Comment by 2bbb** [comment]
hi @jaysonh 

did you try this?

**Comment by jaysonh** [comment]
Hi sorry for the late reply just got round to looking at this. Yes it works, thank you:)

**Comment by 2bbb** [comment]
@jaysonh 
thanks for checking!

and I found bug can't parse unary `-` operator like `-x + y`.
currently I try to fix that.
if you need to use `-x + y`, then please use with another style like `(0 - x) + y` or `y - x` and etc, etc...
